server:
  port: 9999
  context-path: /uaa
security:
  user:
    password: password
spring:
  datasource:
    url: jdbc:hsqldb:file:./target/db/testdb
    username: dbuser
    password: dbpass
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  profiles:
    include: ssl