apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmark-service
  labels:
    app: bookmark-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bookmark-service
  template:
    metadata:
      labels:
        app: bookmark-service
    spec:
      volumes:
        - name: app-logs-volume
          persistentVolumeClaim:
            claimName: app-logs-pvc
      containers:
        - name: bookmark-service
          image: radulecu/bookmark-service
          command: ["java"]
          args:
            - "-XX:MaxRAMPercentage=80"
            - "-XX:+ExitOnOutOfMemoryError"
            - "-jar"
            - "/opt/app/bookmark-service.jar"
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: cloud
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - mountPath: "/opt/log"
              name: app-logs-volume
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "1024Mi"
          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 80
              httpHeaders:
                - name: Accept
                  value: application/json
            failureThreshold: 20
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 80
              httpHeaders:
                - name: Accept
                  value: application/json
            failureThreshold: 5
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: bookmark-service
  labels:
    run: bookmark-service
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30082
  selector:
    app: bookmark-service