server:
  port: ${PORT:9024}
spring:
  application:
    name: client-service-light
security:
  basic:
    enabled: false
#eureka:
#  instance:
#    instanceId: ${random.uuid}
---
spring:
  profiles:
    include: security, eureka, ssl, sslTrustStore

