server:
  port: ${PORT:9023}
spring:
  application:
    name: client-service
security:
  basic:
    enabled: false
#eureka:
#  instance:
#    instanceId: ${random.uuid}
---
swagger:
  proxy: true
spring:
  profiles:
    include: security, eureka, ssl, sslTrustStore, swagger
logging:
  level:
    org.springframework: debug

