server:
  port: ${PORT:9023}
spring:
  application:
    name: client-service
security:
  basic:
    enabled: false
zuul:
  routes:
    path: /bookmark-service/*
    serviceId: bookmark-service
#eureka:
#  instance:
#    instanceId: ${random.uuid}
---
spring:
  profiles:
    include: security, eureka, ssl, sslTrustStore

