server:
  port: ${PORT:9023}
spring:
  application:
    name: client-service
#eureka:
#  instance:
#    instanceId: ${random.uuid}
---
spring:
  profiles:
    include: security, eureka, ssl, truststore

