server:
  port: ${PORT:8084}
spring:
  application:
    name: passport-service
security:
  basic:
    enabled: false
#eureka:
#  instance:
#    instanceId: ${random.uuid}
---
spring:
  profiles:
    include: security, eureka, ssl, sslTrustStore, swagger
