# all interval properties above should be adjusted for performance
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/
    registry-fetch-interval-seconds: 10
    eureka-service-url-poll-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 15
    instance-info-replication-interval-seconds: 10
  instance:
    leaseRenewalIntervalInSeconds: 10
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    hostname: ${server.host:localhost}
    # protocol defined under application-ssl.yml file where the decision is made if ssl is enabled or not
    protocol: ${server.protocol:http}
    statusPageUrl: ${eureka.instance.protocol}://${eureka.instance.hostname}:${server.port}/info
    healthCheckUrl: ${eureka.instance.protocol}://${eureka.instance.hostname}:${server.port}/health
    homePageUrl: ${eureka.instance.protocol}://${eureka.instance.hostName}:${server.port}/
