truststore:
  enabled: true
eureka:
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
system:
  property:
    server:
      ssl:
        trust-store-password: jkspass
        trust-store-type: jks