apiVersion: apps/v1
kind: Deployment
metadata:
  name: passport-service
  labels:
    app: passport-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: passport-service
  template:
    metadata:
      labels:
        app: passport-service
    spec:
      containers:
        - name: passport-service
          image: radulecu/passport-service
          command: ["java"]
          args:
            - "-XX:MaxRAMPercentage=80"
            - "-XX:+ExitOnOutOfMemoryError"
            - "-jar"
            - "/opt/app/passport-service.jar"
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: cloud
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "1024Mi"
          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 80
              httpHeaders:
                - name: Accept
                  value: application/json
            failureThreshold: 20
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 80
              httpHeaders:
                - name: Accept
                  value: application/json
            failureThreshold: 5
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: passport-service
  labels:
    run: passport-service
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30084
  selector:
    app: passport-service