apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-gateway-service
  labels:
    app: resource-gateway-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: resource-gateway-service
  template:
    metadata:
      labels:
        app: resource-gateway-service
    spec:
      containers:
        - name: resource-gateway-service
          image: radulecu/resource-gateway-service
          command: ["java"]
          args:
            - "-XX:MaxRAMPercentage=80"
            - "-XX:+ExitOnOutOfMemoryError"
            - "-jar"
            - "/opt/app/resource-gateway-service.jar"
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: cloud
            - name: eureka.client.enabled
              value: "false"
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "1024Mi"
          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 80
              httpHeaders:
                - name: Accept
                  value: application/json
            failureThreshold: 20
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 80
              httpHeaders:
                - name: Accept
                  value: application/json
            failureThreshold: 5
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: resource-gateway-service
  labels:
    run: resource-gateway-service
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31025
  selector:
    app: resource-gateway-service