apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1401
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/nfs_pv/pv1
    server: 192.168.33.14
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1402
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
      - ReadWriteOnce
      - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/nfs_pv/pv2
    server: 192.168.33.14
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: pv1501
#spec:
#  capacity:
#    storage: 10Gi
#  volumeMode: Filesystem
#  accessModes:
#      - ReadWriteOnce
#      - ReadWriteMany
#  persistentVolumeReclaimPolicy: Recycle
#  mountOptions:
#    - hard
#    - nfsvers=4.1
#  nfs:
#    path: /mnt/nfs_pv/pv1
#    server: 192.168.33.15
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: pv1502
#spec:
#  capacity:
#    storage: 10Gi
#  volumeMode: Filesystem
#  accessModes:
#      - ReadWriteOnce
#      - ReadWriteMany
#  persistentVolumeReclaimPolicy: Recycle
#  mountOptions:
#    - hard
#    - nfsvers=4.1
#  nfs:
#    path: /mnt/nfs_pv/pv2
#    server: 192.168.33.15
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1601
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
      - ReadWriteOnce
      - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/nfs_pv/pv1
    server: 192.168.33.16
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1602
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/nfs_pv/pv2
    server: 192.168.33.16
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: pv1701
#spec:
#  capacity:
#    storage: 10Gi
#  volumeMode: Filesystem
#  accessModes:
#      - ReadWriteOnce
#      - ReadWriteMany
#  persistentVolumeReclaimPolicy: Recycle
#  mountOptions:
#    - hard
#    - nfsvers=4.1
#  nfs:
#    path: /mnt/nfs_pv/pv1
#    server: 192.168.33.17
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: pv1702
#spec:
#  capacity:
#    storage: 10Gi
#  volumeMode: Filesystem
#  accessModes:
#      - ReadWriteOnce
#      - ReadWriteMany
#  persistentVolumeReclaimPolicy: Recycle
#  mountOptions:
#    - hard
#    - nfsvers=4.1
#  nfs:
#    path: /mnt/nfs_pv/pv2
#    server: 192.168.33.17
