server:
  port: ${PORT:8761}
spring:
  application:
    name: eureka-service
security:
  basic:
    enabled: false
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enable-self-preservation: false
    responseCacheAutoExpirationInSeconds: 10
#security:
#  basic:
#    enabled: true
#  user:
#      name: user
#      password: password
---
spring:
  profiles:
    include: sslTrustStore, security
