server:
  port: ${PORT:8083}
spring:
  jpa:
    generate-ddl: true
  application:
    name: contact-service
#eureka:
#  instance:
#    instanceId: ${random.uuid}
---
spring:
  profiles:
    include: security, eureka, ssl, truststore

