eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:eurekasecret@localhost:8761/eureka/
    # all interval properties below may require to be adjusted for performance
    registry-fetch-interval-seconds: 10
    eureka-service-url-poll-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 15
    instance-info-replication-interval-seconds: 10
  instance:
    leaseRenewalIntervalInSeconds: 10
    securePortEnabled: ${ssl.enabled:false}
    securePort: ${server.port}
    hostname: ${server.host:localhost}
    # protocol defined under application-ssl.yml file where the decision is made if ssl is enabled or not
    protocol: ${server.protocol:http}
    statusPageUrl: ${eureka.instance.protocol}://${eureka.instance.hostname}:${server.port}/info
    healthCheckUrl: ${eureka.instance.protocol}://${eureka.instance.hostname}:${server.port}/health
    homePageUrl: ${eureka.instance.protocol}://${eureka.instance.hostName}:${server.port}/
