= Security dependencies

To access any resource via SSO you need to get a token from the security service (see security-sso-auth-server module) and use it to get the resource.

In this chase we can have 2 types of secured services

- resource servers
    * used for providing resources
    * to access it you (or the client who is accessing it) have to provide the token received from the security service
- client server
    * can be either a web application (javascript/angular)
    * has to authenticate
        ** in chase of simple spring boot rest/mvc service it is done via OAuth2 (@EnableOAuth2Sso)
        ** in chase of javascript

== Accessing a resource server
curl -k -X POST -vu acme:acmesecret https://localhost:9999/uaa/oauth/token -H "Accept: application/json" -d "password=spring&username=jlong&grant_type=password&scope=openid&client_secret=acmesecret&client_id=acme"

curl -k http://localhost:8082/bookmarks/jlong -H "Authorization: Bearer <TOKEN>"

curl -k http://localhost:8083/contacts/jlong -H "Authorization: Bearer <TOKEN>"

curl -k http://localhost:8084/passport/jlong -H "Authorization: Bearer <TOKEN>"

== SSL security

=== Generating keystore, certificate and truststore files command

keytool -genkey -alias jksalias -keyalg RSA -keystore my.jks -deststoretype JKS -validity 1825 -keypass jkspass -storepass jkspass -dname "CN=localhost, OU=N/A, O=N/A, L=Bucharest, ST=Romania, C=RO correct?"

keytool -export -alias jksalias -keystore my.jks -file my.cer -storepass jkspass

keytool -importcert -keystore my.truststore -alias jksalias -storepass jkspass -file my.cer -noprompt

The first command is to generate a jks keystore. It will be used to enable the SSL/TSL for the server.
Next a certificate for the keystore is generated.
Using the certificate we can nou create the truststore. The role of the trustore is to be able to use the SSL/TSL signed service.

=== Viewing  keystore details

keytool -list -v -alias jksalias -keystore ./my.jks -storepass jkspass

== Further read
- Securing Your Cloud-native Microservice Architecture in Spring
    * https://ordina-jworks.github.io/microservices/2017/09/26/Secure-your-architecture-part1.html
    * http://www.swisspush.org/security/2016/10/17/oauth2-in-depth-introduction-for-enterprises
        ** Also provides details about how to configure GlobalMethodSecurity
    * http://stytex.de/blog/2016/02/01/spring-cloud-security-with-oauth2/
    * https://piotrminkowski.wordpress.com/2017/02/22/microservices-security-with-oauth2/
- Keystore/Truststore
    * https://docs.spring.io/spring-cloud-dataflow/docs/1.1.0.M1/reference/html/getting-started-security.html
    * https://drissamri.be/blog/java/enable-https-in-spring-boot/
- Webinar Replay: Security for Microservices with Spring and OAuth2
    * https://spring.io/blog/2014/11/07/webinar-replay-security-for-microservices-with-spring-and-oauth2
- Security with spring: Baeldung
    * http://www.baeldung.com/security-spring
    * http://www.baeldung.com/rest-api-spring-oauth2-angularjs