= Security dependencies

To access any resource via SSO you need to get a token from the security service (see security-sso-auth-server module) and use it to get the resource.

In this chase we can have 2 types of secured services

- resource services
    * used for providing resources
    * to access it you (or the client who is accessing it) have to provide the token received from the security service
- client services
    * can be either a web application (javascript/angular)
    * has to authenticate
        ** in chase of simple spring boot rest/mvc service it is done via OAuth2 (@EnableOAuth2Sso)
        ** in chase of javascript you have to acquire the token from the security service and forward it in the header at future requests

== Usage
* Security for a resource server is enabled using security-sso-component by:
    ** using ro.rasel:ssl-component maven dependency
    ** include ResourceSecurityClientComponent class in SpringApplication.run() source classes
    ** default configuration by including security profile in configuration file (which ends up including application-security.yml
* To enable a client server instead of ResourceSecurityClientComponent class we will include WebSecurityClientComponent in SpringApplication.run() source classes

== Example services using security
* Resource servers:
    ** bookmark-service
    ** contact-service
    ** passport-service
* client service
    ** client-service
    ** client-service-light
    ** security-sso-ui

== Accessing a resource server
curl -k -X POST -vu acme:acmesecret https://localhost:9999/sso/oauth/token -H "Accept: application/json" -d "password=spring&username=jlong&grant_type=password&scope=openid&client_secret=acmesecret&client_id=acme"

curl -k https://localhost:8082/users/jlong/bookmarks -H "Authorization: Bearer <TOKEN>"

curl -k https://localhost:8083/users/jlong/contacts -H "Authorization: Bearer <TOKEN>"

curl -k https://localhost:8084/users/jlong/passport -H "Authorization: Bearer <TOKEN>"

== Further read
- Securing Your Cloud-native Microservice Architecture in Spring
    * https://ordina-jworks.github.io/microservices/2017/09/26/Secure-your-architecture-part1.html
    * http://www.swisspush.org/security/2016/10/17/oauth2-in-depth-introduction-for-enterprises
        ** Also provides details about how to configure GlobalMethodSecurity
    * http://stytex.de/blog/2016/02/01/spring-cloud-security-with-oauth2/
    * https://piotrminkowski.wordpress.com/2017/02/22/microservices-security-with-oauth2/
- Keystore/Truststore
    * https://docs.spring.io/spring-cloud-dataflow/docs/1.1.0.M1/reference/html/getting-started-security.html
    * https://drissamri.be/blog/java/enable-https-in-spring-boot/
- Webinar Replay: Security for Microservices with Spring and OAuth2
    * https://spring.io/blog/2014/11/07/webinar-replay-security-for-microservices-with-spring-and-oauth2
- Security with spring: Baeldung
    * http://www.baeldung.com/security-spring
    * http://www.baeldung.com/rest-api-spring-oauth2-angularjs
- JWT (JSON Web Tokens)
    * https://jwt.io/
- Authentication and Authorisation
    * OAuth: https://oauth.net/
    * OpenID vs OAuth2 vs SAML https://spin.atomicobject.com/2016/05/30/openid-oauth-saml/
