server:
  security:
   url: https://localhost:9999
zuul:
  routes:
    user:
      path: /user/**
      url: ${server.security.url}/uaa/user
security:
  user:
    password: password
  oauth2:
    client:
      accessTokenUri: ${server.security.url}/uaa/oauth/token
      userAuthorizationUri: ${server.security.url}/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      userInfoUri: ${server.security.url}/uaa/user
  basic:
    enabled: false

#histrix strategy is required to avoid errors caused by the fact that hystrix handles requests in a different thread causing unexpected errors
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
spring:
  profiles:
    include: ssl, truststore
# setup eureka properties will be ignored if eureka unused
eureka:
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    hostname: ${server.host:localhost}
    statusPageUrl: https://${eureka.instance.hostname}:${server.port}/info
    healthCheckUrl: https://${eureka.instance.hostname}:${server.port}/health
    homePageUrl: https://${eureka.instance.hostName}:${server.port}/