server:
  security:
   url: https://localhost:9999
zuul:
  routes:
    user:
      path: /user/**
      url: ${server.security.url}/uaa/user
security:
  enabled: true
  user:
    password: password
  oauth2:
    client:
      accessTokenUri: ${server.security.url}/uaa/oauth/token
      userAuthorizationUri: ${server.security.url}/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      userInfoUri: ${server.security.url}/uaa/user
  basic:
    enabled: false
# hystrix strategy is required to avoid errors caused by the fact that hystrix handles requests in a different thread causing unexpected errors over feign
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
