zuul:
  routes:
    user:
      path: /user/**
      url: http://localhost:9999/uaa/user
security:
  user:
    password: password
  oauth2:
    client:
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      userInfoUri: http://localhost:9999/uaa/user
  basic:
    enabled: false
#histrix strategy is required to avoid errors caused by the fact that hystrix handles requests in a different thread causing unexpected errors
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
